from aws_cdk import (
    Stack,
    CfnOutput,
    RemovalPolicy,
    Duration,
    aws_secretsmanager as secretsmanager,
    aws_s3 as s3,
)
from constructs import Construct


class SecurityStack(Stack):
    """Secrets Manager credentials + S3 backup bucket.

    No customer-managed KMS key is created (extra ~$1/month with no functional
    benefit here); Secrets Manager's and S3's default AWS-managed encryption is
    used. Never hardcode secrets: the DB password is generated by Secrets
    Manager itself and read by EC2 UserData / Kafka Connect / dbt at runtime.
    Kafka Connect plugin JARs are fetched directly from Maven Central by the
    Kafka Connect EC2 instance's UserData (it has its own NAT internet path),
    so no S3 staging bucket is needed for them.
    """

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        project = self.node.try_get_context("project_name")
        db_name = self.node.try_get_context("db_name")

        self.db_secret = secretsmanager.Secret(
            self,
            "DbSecret",
            secret_name=f"{project}/postgres/credentials",
            description="PostgreSQL credentials for the on-prem-simulation EC2 instance (iot db)",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template=f'{{"username":"iot_admin","dbname":"{db_name}","port":5432}}',
                generate_string_key="password",
                exclude_punctuation=True,
                password_length=24,
            ),
        )

        self.backup_bucket = s3.Bucket(
            self,
            "BackupBucket",
            bucket_name=f"{project}-iot-backup-{self.account}-{self.region}",
            versioned=True,
            encryption=s3.BucketEncryption.S3_MANAGED,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            removal_policy=RemovalPolicy.RETAIN,
            lifecycle_rules=[
                s3.LifecycleRule(
                    id="transition-old-backups",
                    enabled=True,
                    transitions=[
                        s3.Transition(
                            storage_class=s3.StorageClass.INFREQUENT_ACCESS,
                            transition_after=Duration.days(30),
                        )
                    ],
                )
            ],
        )

        CfnOutput(self, "DbSecretArn", value=self.db_secret.secret_arn)
        CfnOutput(self, "BackupBucketName", value=self.backup_bucket.bucket_name)
