from aws_cdk import (
    Stack,
    CfnOutput,
    RemovalPolicy,
    Duration,
    aws_secretsmanager as secretsmanager,
    aws_s3 as s3,
    aws_s3_deployment as s3deploy,
)
from constructs import Construct


class SecurityStack(Stack):
    """Secrets Manager credentials + S3 buckets (backup, Connect plugins).

    No customer-managed KMS key is created (extra ~$1/month with no functional
    benefit here); Secrets Manager's and S3's default AWS-managed encryption is
    used. Never hardcode secrets: the DB password is generated by Secrets
    Manager itself and read by EC2 UserData / Kafka Connect / dbt at runtime.
    """

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        project = self.node.try_get_context("project_name")
        db_name = self.node.try_get_context("db_name")

        self.db_secret = secretsmanager.Secret(
            self,
            "DbSecret",
            secret_name=f"{project}/postgres/credentials",
            description="PostgreSQL credentials for the on-prem-simulation EC2 instance (iot db)",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template=f'{{"username":"iot_admin","dbname":"{db_name}","port":5432}}',
                generate_string_key="password",
                exclude_punctuation=True,
                password_length=24,
            ),
        )

        self.backup_bucket = s3.Bucket(
            self,
            "BackupBucket",
            bucket_name=f"{project}-iot-backup-{self.account}-{self.region}",
            versioned=True,
            encryption=s3.BucketEncryption.S3_MANAGED,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            removal_policy=RemovalPolicy.RETAIN,
            lifecycle_rules=[
                s3.LifecycleRule(
                    id="transition-old-backups",
                    enabled=True,
                    transitions=[
                        s3.Transition(
                            storage_class=s3.StorageClass.INFREQUENT_ACCESS,
                            transition_after=Duration.days(30),
                        )
                    ],
                )
            ],
        )

        self.plugins_bucket = s3.Bucket(
            self,
            "ConnectPluginsBucket",
            bucket_name=f"{project}-connect-plugins-{self.account}-{self.region}",
            versioned=True,
            encryption=s3.BucketEncryption.S3_MANAGED,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            removal_policy=RemovalPolicy.DESTROY,
            auto_delete_objects=True,
        )

        # Uploads cdk/assets/plugins/<name>/*.zip produced by scripts/fetch-connector-plugins.sh
        self.jdbc_plugin_deployment = s3deploy.BucketDeployment(
            self,
            "JdbcSinkPluginDeploy",
            sources=[s3deploy.Source.asset("assets/plugins/jdbc-sink")],
            destination_bucket=self.plugins_bucket,
            destination_key_prefix="jdbc-sink",
            prune=False,
            extract=False,
        )
        self.debezium_plugin_deployment = s3deploy.BucketDeployment(
            self,
            "DebeziumPluginDeploy",
            sources=[s3deploy.Source.asset("assets/plugins/debezium-postgres")],
            destination_bucket=self.plugins_bucket,
            destination_key_prefix="debezium-postgres",
            prune=False,
            extract=False,
        )

        CfnOutput(self, "DbSecretArn", value=self.db_secret.secret_arn)
        CfnOutput(self, "BackupBucketName", value=self.backup_bucket.bucket_name)
        CfnOutput(self, "PluginsBucketName", value=self.plugins_bucket.bucket_name)
