-- ============================================================================
-- Streamlit dashboard setup — MANUAL, run in Snowsight as ACCOUNTADMIN
-- Account: <SNOWFLAKE_ACCOUNT>
-- ============================================================================
-- Creates a dedicated, strictly read-only role/user for the Streamlit
-- dashboard, separate from KAFKA_CONNECTOR_ROLE (ingestion) and DBT_ROLE
-- (transformation, owns the Gold schema). The dashboard must only ever
-- read the Gold layer, so this role is granted SELECT on the Gold schema
-- only - it has no visibility into BRONZE or SILVER, and no CREATE
-- privileges at all. This enforces the "Gold only" requirement at the
-- database privilege layer, not just in application code.
--
-- CORRECTION (post-deploy): dbt's default schema-naming behavior
-- concatenates the connection's default schema (BRONZE, from
-- dbt/profiles.yml) with each model's custom `+schema` config, so the Gold
-- layer actually lives in IOT_PLATFORM.BRONZE_GOLD, not IOT_PLATFORM.GOLD.
-- This script originally referenced GOLD, which does not exist, so the
-- schema/table GRANT statements below failed the first time this was run.
-- Fixed to reference BRONZE_GOLD throughout. See docs/deployment/14-streamlit-dashboard.md
-- "Issues encountered" for full detail. This script is idempotent
-- (CREATE ... IF NOT EXISTS, and GRANTs are safe to re-run) so re-running it
-- in full is safe even though the ROLE/USER/KEY statements already applied.
-- ============================================================================

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS STREAMLIT_ROLE
  COMMENT = 'IoT Hackathon - Streamlit dashboard role (read-only, Gold layer only)';

CREATE USER IF NOT EXISTS STREAMLIT_USER
  DEFAULT_ROLE      = STREAMLIT_ROLE
  DEFAULT_WAREHOUSE = IOT_INGEST_WH
  DEFAULT_NAMESPACE = 'IOT_PLATFORM.BRONZE_GOLD'
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'IoT Hackathon - Streamlit dashboard service user (key-pair auth only)';

-- Public key generated by you; private key stored only in AWS Secrets
-- Manager (iot-hackathon/snowflake/streamlit-key), never in this repo.
ALTER USER STREAMLIT_USER SET RSA_PUBLIC_KEY='<YOUR_RSA_PUBLIC_KEY_BODY>';

GRANT ROLE STREAMLIT_ROLE TO USER STREAMLIT_USER;

-- Read-only on the Gold schema only. No BRONZE/SILVER usage, no CREATE
-- anything, no ownership. FUTURE grants so new Gold models don't require
-- a follow-up ALTER when dbt adds tables/views later. (The direct SELECT
-- grants on today's objects were already applied via DBT_ROLE, since it
-- owns this schema as its creator and doesn't need ACCOUNTADMIN for that -
-- only the FUTURE grants below require ACCOUNTADMIN's MANAGE GRANTS.)
GRANT USAGE ON WAREHOUSE IOT_INGEST_WH TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON DATABASE IOT_PLATFORM TO ROLE STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA IOT_PLATFORM.BRONZE_GOLD TO ROLE STREAMLIT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA IOT_PLATFORM.BRONZE_GOLD TO ROLE STREAMLIT_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA IOT_PLATFORM.BRONZE_GOLD TO ROLE STREAMLIT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA IOT_PLATFORM.BRONZE_GOLD TO ROLE STREAMLIT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA IOT_PLATFORM.BRONZE_GOLD TO ROLE STREAMLIT_ROLE;

-- Verification
SHOW ROLES LIKE 'STREAMLIT_ROLE';
SHOW USERS LIKE 'STREAMLIT_USER';
DESC USER STREAMLIT_USER;  -- confirm RSA_PUBLIC_KEY_FP is set (not null)
SHOW GRANTS TO ROLE STREAMLIT_ROLE;
