-- ============================================================================
-- dbt Core setup — MANUAL, run in Snowsight as ACCOUNTADMIN
-- Account: <SNOWFLAKE_ACCOUNT>
-- ============================================================================
-- Creates a dedicated role/user for dbt, separate from KAFKA_CONNECTOR_ROLE
-- (which is scoped narrowly to Bronze ingestion only and has no CREATE SCHEMA
-- privilege at the database level - dbt needs to create/own the SILVER and
-- GOLD schemas, so it gets its own least-privilege identity rather than
-- widening the ingestion connector's permissions).
-- ============================================================================

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS DBT_ROLE
  COMMENT = 'IoT Hackathon - dbt Core transformation role';

CREATE USER IF NOT EXISTS DBT_USER
  DEFAULT_ROLE      = DBT_ROLE
  DEFAULT_WAREHOUSE = IOT_INGEST_WH
  DEFAULT_NAMESPACE = 'IOT_PLATFORM.BRONZE'
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'IoT Hackathon - dbt Core service user (key-pair auth only)';

-- Public key generated by you; private key stored only in AWS Secrets
-- Manager (iot-hackathon/snowflake/dbt-key), never in this repo.
ALTER USER DBT_USER SET RSA_PUBLIC_KEY='<YOUR_RSA_PUBLIC_KEY_BODY>';

GRANT ROLE DBT_ROLE TO USER DBT_USER;

-- Minimum required: read the Bronze source table, create/own Silver and
-- Gold schemas so dbt can build and manage its own models within them.
GRANT USAGE ON WAREHOUSE IOT_INGEST_WH TO ROLE DBT_ROLE;
GRANT USAGE ON DATABASE IOT_PLATFORM TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA IOT_PLATFORM.BRONZE TO ROLE DBT_ROLE;
GRANT SELECT ON TABLE IOT_PLATFORM.BRONZE.IOT_EVENTS_RAW TO ROLE DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE IOT_PLATFORM TO ROLE DBT_ROLE;

-- Verification
SHOW ROLES LIKE 'DBT_ROLE';
SHOW USERS LIKE 'DBT_USER';
DESC USER DBT_USER;  -- confirm RSA_PUBLIC_KEY_FP is set (not null)
SHOW GRANTS TO ROLE DBT_ROLE;
