-- ============================================================================
-- STEP 1 — Snowflake environment setup (MANUAL — run in Snowsight or SnowSQL)
-- Account: JCANAAG-YCB85704
-- ============================================================================
-- Run this entire script as a role with sufficient privileges to create
-- warehouses, databases, roles, and users (e.g. ACCOUNTADMIN, or SECURITYADMIN
-- + SYSADMIN for a fresh account with nothing created yet).
--
-- Nothing in this project's AWS account exists inside Snowflake yet, so every
-- object below is created from scratch. Safe to re-run: every CREATE uses
-- IF NOT EXISTS / OR REPLACE where that doesn't risk clobbering real data.
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- ----------------------------------------------------------------------------
-- 1. Warehouse — compute for the Kafka Connector's ingestion (Snowpipe-backed)
-- ----------------------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS IOT_INGEST_WH
  WAREHOUSE_SIZE      = 'XSMALL'
  AUTO_SUSPEND         = 60
  AUTO_RESUME          = TRUE
  INITIALLY_SUSPENDED  = TRUE
  COMMENT              = 'IoT Hackathon - Kafka Connector ingestion warehouse';

-- ----------------------------------------------------------------------------
-- 2. Database
-- ----------------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS IOT_PLATFORM
  COMMENT = 'IoT Hackathon - Bronze/Silver/Gold data platform';

-- ----------------------------------------------------------------------------
-- 3. Schema — Bronze layer (raw, untransformed CDC events)
-- ----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS IOT_PLATFORM.BRONZE
  COMMENT = 'Bronze layer - raw Debezium CDC events, schema-on-read (VARIANT)';

-- ----------------------------------------------------------------------------
-- 4. Role — least-privilege role for the Kafka Connector only
-- ----------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS KAFKA_CONNECTOR_ROLE
  COMMENT = 'IoT Hackathon - role for the Snowflake Kafka Connector service user';

-- ----------------------------------------------------------------------------
-- 5. User — service account for the Kafka Connector, key-pair auth only
--    (no password - RSA_PUBLIC_KEY set below; this account cannot log in
--    via username/password at all, matching the no-static-password pattern
--    used everywhere else in this project)
-- ----------------------------------------------------------------------------
CREATE USER IF NOT EXISTS KAFKA_CONNECTOR_USER
  DEFAULT_ROLE      = KAFKA_CONNECTOR_ROLE
  DEFAULT_WAREHOUSE = IOT_INGEST_WH
  DEFAULT_NAMESPACE = 'IOT_PLATFORM.BRONZE'
  COMMENT           = 'IoT Hackathon - Snowflake Kafka Connector service user (key-pair auth only)'
  MUST_CHANGE_PASSWORD = FALSE;

-- ----------------------------------------------------------------------------
-- 6. RSA key-pair authentication
--    Public key generated by Claude (Step 2, AWS-side) - private key is
--    stored ONLY in AWS Secrets Manager
--    (iot-hackathon/snowflake/kafka-connector-key), never in this repo.
-- ----------------------------------------------------------------------------
ALTER USER KAFKA_CONNECTOR_USER SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm9uvS4Xql4sbeP+CkkQTImG5Gg4Vb9FGyqii6Yjtuggfzn9jBTxwWATBfcZWBT/yj4oAQ4o0kjFv5cW8OVf99jSeXYO8FeOF0CXluVW1nnXJRW9PgMM+W6x+WzP5X0jBEmWJMwTlimoKgfw6ONLtcxObnqKbH6T6SM7v+oYes9lB/NvNa/WrfAcXFwSQzF8hnSBOwNeKCbJIQ66FvSfbDKMZa4f4zwCX4hwdaV7okl+uo+8MMUusk+j2QNobXvZItUoY4HMhwNOzhBx8b/b7mwjuP/5leN/JqP6x4dj691+45m7ta0kpVGFnSstYafnyzbnggxhMIC9thzvVQLofdQIDAQAB';

GRANT ROLE KAFKA_CONNECTOR_ROLE TO USER KAFKA_CONNECTOR_USER;

-- ----------------------------------------------------------------------------
-- 7. Grants — minimum required for the Snowflake Kafka Connector to operate.
--    The connector uses Snowpipe internally, so it needs to create/manage its
--    own internal stage and pipe objects per topic-partition, in addition to
--    writing rows into the target table.
-- ----------------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE IOT_INGEST_WH TO ROLE KAFKA_CONNECTOR_ROLE;

GRANT USAGE ON DATABASE IOT_PLATFORM TO ROLE KAFKA_CONNECTOR_ROLE;

GRANT USAGE ON SCHEMA IOT_PLATFORM.BRONZE TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE TABLE ON SCHEMA IOT_PLATFORM.BRONZE TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE STAGE ON SCHEMA IOT_PLATFORM.BRONZE TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE PIPE ON SCHEMA IOT_PLATFORM.BRONZE TO ROLE KAFKA_CONNECTOR_ROLE;

-- ----------------------------------------------------------------------------
-- 8. Bronze table — IOT_EVENTS_RAW, using the standard Snowflake Kafka
--    Connector table shape: two VARIANT columns. This is deliberate for a
--    Bronze layer - it preserves the FULL Debezium CDC envelope
--    (before/after/source/op/ts_ms) exactly as received, unparsed. Typed,
--    per-field columns belong in the Silver layer (a future dbt task), not
--    here - Bronze is schema-on-read by design.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS IOT_PLATFORM.BRONZE.IOT_EVENTS_RAW (
  RECORD_METADATA VARIANT COMMENT 'Kafka metadata: topic, partition, offset, timestamp, key',
  RECORD_CONTENT  VARIANT COMMENT 'Full Debezium CDC envelope: before, after, source, op, ts_ms'
)
COMMENT = 'Bronze layer - raw Debezium CDC events from cdc.public.iot_events, ingested by the Snowflake Kafka Connector';

-- The connector's role needs to write into (and own the lifecycle of) this
-- table, since the Kafka Connector may alter it as part of normal operation.
GRANT OWNERSHIP ON TABLE IOT_PLATFORM.BRONZE.IOT_EVENTS_RAW TO ROLE KAFKA_CONNECTOR_ROLE
  REVOKE CURRENT GRANTS;

-- ----------------------------------------------------------------------------
-- Verification queries — run these after the script to confirm everything
-- above was created correctly before approving connector deployment.
-- ----------------------------------------------------------------------------
SHOW WAREHOUSES LIKE 'IOT_INGEST_WH';
SHOW DATABASES LIKE 'IOT_PLATFORM';
SHOW SCHEMAS LIKE 'BRONZE' IN DATABASE IOT_PLATFORM;
SHOW ROLES LIKE 'KAFKA_CONNECTOR_ROLE';
SHOW USERS LIKE 'KAFKA_CONNECTOR_USER';
DESC USER KAFKA_CONNECTOR_USER;  -- confirm RSA_PUBLIC_KEY_FP is set (not null)
SHOW TABLES LIKE 'IOT_EVENTS_RAW' IN SCHEMA IOT_PLATFORM.BRONZE;
SHOW GRANTS TO ROLE KAFKA_CONNECTOR_ROLE;
